import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layout-wrapper";
import AppProviders from "@/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frakt",
  description: "Generated by create next app",
};

// const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AppProviders>
          <LayoutWrapper>
            <div
              className={`sheet-backdrop fixed top-0 right-0 w-screen h-screen bg-[#42424270] z-30`}
              style={{ display: "none" }}
            ></div>
            {children}
          </LayoutWrapper>
        </AppProviders>
      </body>
    </html>
  );
}
